// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  JWT_SECRET: string
  GITHUB_USER: string
  GITHUB_TOKEN: string
  GITHUB_REPO: string
  DB: D1Database
}
